### ISSUE TITLE
[question]How nats client api is to do with async callback , & seen lambda in api doc only support over jdk1.8+?

### ISSUE THREAD

**Issue by fadeAce** [nats-io/java-nats#129]

**Comment by zbyzhengzong** [comment]
such as doing 
sub(topic, message,m->{
   callback();
})
was it a native implement to go-based Nats-server , and will it be slower than go api (gnats)?

**Comment by ColinSullivan1** [comment]
@zbyzhengzong , Thank you for using NATS!

When creating an asynchronous callback, you can either use java lambda style functions, or for previous java version compatibility, pass an object that implements the `MessageHandler.onMessage(Message msg);` interface, found [here](https://github.com/nats-io/java-nats/blob/0.5.3/src/main/java/io/nats/client/MessageHandler.java#L20).

The java client was based on our canonical client, [go-nats](https://github.com/nats-io/go-nats).  In most situations, the `go-nats` client will be faster because it is compiled.

Does this answer your questions?

**Comment by zbyzhengzong** [comment]
Thanks for reply!
And i'm sure to use Nats ClientAPI ,but what confuse me is that i'm sure to use a J-api but may Clients that using J-api slower than G-api , so will it possible that i'm to use a cross-lang call from Java to call go api using dynamic lib build by golang api exported in cgo buildmode(like: go build -o xxx.so -buildmode=c-shared xxx.go).

**Comment by sasbury** [comment]
Version 2 supports lamdas when using dispatchers:

Dispatcher d = nc.createDispatcher((msg) -> {
        String response = new String(msg.getData(), StandardCharsets.UTF_8);
        ...
    });

    d.subscribe("subject");

There are a few more examples in the examples folder that use this pattern as well.
