### ISSUE TITLE
publish does not produce exception in case no server connection

### ISSUE THREAD

**Issue by lysakaleksey** [nats-io/java-nats#140]
The publish method does not produce exception in case no server connection.

Code snippet to reproduce:

```
public class TestPublish {
	public static void main(String[] args) {
		try {
			String url = "nats://localhost:4222";
			io.nats.client.ConnectionFactory cf = new io.nats.client.ConnectionFactory(url);
			io.nats.client.Connection sc = cf.createConnection();
			System.out.println("Shutdown the gnatsd right now");
			Thread.sleep(10_000);
			String payload = "{ \"foo\":\"bar\" }";
			sc.publish("test", payload.getBytes());
			System.out.println("Last Exception = " + sc.getLastException());
		} catch (Exception ex) {
			ex.printStackTrace();
		}
	}
}
```

**Comment by lysakaleksey** [comment]
Tried on io.nats:jnats:1.0 & 1.1-SNAPSHOT versions

**Comment by kozlovic** [comment]
This is because by default the client library will try to reconnect. While doing so, all published messages and creation of subscriptions are buffered and flushed on successful reconnect. The buffer is limited (but configurable). If the buffer is full, then you would get an error reporting this.
If you want the publish call to fail in above test, you would need to disallow reconnect.
```
...
cf.setReconnectAllowed(false);
io.nats.client.Connection sc = cf.createConnection();
...
```

**Comment by lysakaleksey** [comment]
Got it. Thanks
