### ISSUE TITLE
How to integrate Nats into the Spring Boot framework

### ISSUE THREAD

**Issue by wanlinus** [nats-io/java-nats#173]
How to integrate Nats into the Spring Boot framework and use it like RabbitMQ. In Spring Boot use RabbitMQ only use Annotation RabbitListener.But the java-nats have no some annotations like that

**Comment by dstrelec** [comment]
2 years ago I have started my own project for integration of Nats and Spring Boot. Have never finish the project but basic use cases were working fine. You can check it at at https://github.com/dstrelec/nats

**Comment by sasbury** [comment]
I will be honest, I don't use spring enough to comment, perhaps someone on the slack channel could help - https://natsio.slack.com/messages/C1KU01HD2 for java or https://natsio.slack.com/messages/C069GSYFP for general NATS.

**Comment by wanlinus** [comment]
Thx, I use [java-nats](https://github.com/cloudfoundry-community/java-nats) in my project,but always apear an error, Maximum Control Line Exceeded.But I don't know how can i solve it.

**Comment by sasbury** [comment]
Usually if you are exceeding it is because you have very long subject names. I forget the default, maybe 256 or 512. You can set on the server. The java client also lets you set it locally, which will prevent the server error and just error on the client. So if you change it on the server, change it on the client as well. Note - not all client libs support the setting.

There is some doc and an example on the new site:

https://nats.io/doc/writing_applications/connection_options/?lang=java

**Comment by wanlinus** [comment]
Thank you very much for your help. My problem has been solved
